/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as treasuryFactorySol from "./TreasuryFactory.sol";
export type { treasuryFactorySol };
export type { MockERC20 } from "./MockERC20";
export type { MockSafe } from "./MockSafe";
