/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TreasuryFactoryInterface extends Interface {
  getFunction(nameOrSignature: "createTreasury"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TreasuryCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createTreasury",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike[],
      AddressLike,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "createTreasury",
    data: BytesLike
  ): Result;
}

export namespace TreasuryCreatedEvent {
  export type InputTuple = [treasury: AddressLike];
  export type OutputTuple = [treasury: string];
  export interface OutputObject {
    treasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TreasuryFactory extends BaseContract {
  connect(runner?: ContractRunner | null): TreasuryFactory;
  waitForDeployment(): Promise<this>;

  interface: TreasuryFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createTreasury: TypedContractMethod<
    [
      safe: AddressLike,
      minimumAmount: BigNumberish,
      deadline: BigNumberish,
      whitelistedTokens: AddressLike[],
      depositToken: AddressLike,
      depositAmount: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createTreasury"
  ): TypedContractMethod<
    [
      safe: AddressLike,
      minimumAmount: BigNumberish,
      deadline: BigNumberish,
      whitelistedTokens: AddressLike[],
      depositToken: AddressLike,
      depositAmount: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "TreasuryCreated"
  ): TypedContractEvent<
    TreasuryCreatedEvent.InputTuple,
    TreasuryCreatedEvent.OutputTuple,
    TreasuryCreatedEvent.OutputObject
  >;

  filters: {
    "TreasuryCreated(address)": TypedContractEvent<
      TreasuryCreatedEvent.InputTuple,
      TreasuryCreatedEvent.OutputTuple,
      TreasuryCreatedEvent.OutputObject
    >;
    TreasuryCreated: TypedContractEvent<
      TreasuryCreatedEvent.InputTuple,
      TreasuryCreatedEvent.OutputTuple,
      TreasuryCreatedEvent.OutputObject
    >;
  };
}
